### ISSUE TITLE
Does this allow the ability to run last task?

### ISSUE THREAD

**Issue by krishnakumarg1984** [mg979/tasks.vim#12]
Asyntasks.vim recently introduced the ability to re-run the last run task. Does this feature exist here?

Also, what do you mean by parallel? With Asynctasks, I am already able to run `gcc` for parallel compilation. Is this what you mean?

**Comment by mg979** [comment]
> Asyntasks.vim recently introduced the ability to re-run the last run task. Does this feature exist here?

No. I generally use mappings to run tasks, so I can't see a use case for this. If run from the command line, you can just reselect the command from the command line.

> Also, what do you mean by parallel? With Asynctasks, I am already able to run gcc for parallel compilation. Is this what you mean?

I seem to remember that Asynctasks.vim can run a single task at a time. Parallel to vim yes, but you can't run multiple parallel async tasks. Not sure if I'm right, though.

**Comment by krishnakumarg1984** [comment]
Thank you for the clarifications.
