### ISSUE TITLE
pass cwd to cmd

### ISSUE THREAD

**Issue by Konfekt** [mg979/tasks.vim#2]
Similar to [AsyncRun](https://github.com/skywind3000/asyncrun.vim)'s `-cwd` parameter to set the current work dir of the run command, could such a parameter be passed to Async as well?

**Comment by mg979** [comment]
Default commands don't accept options, because all arguments are the shell command with its arguments. Changing that would mean needing quotes, and I don't want that.

You can either:

1. use the `async#cmd(command, mode, options)` function (read the documentation for that)
2. use a project `.tasks` file, where you define project tasks, and their options (also in the documentation)

Personally the only time I use a different `cwd` is to run tests, and I have a `.tasks` file with a task:

```
[run-tests]
command=sh run_tests.sh
cwd=$ROOT/test
output=terminal
```

**Comment by Konfekt** [comment]
> use the async#cmd(command, mode, options) function (read the documentation for that)

Is [this documentation](https://github.com/mg979/tasks.vim/blob/master/docs/1-async.md#gasync_jobs) meant? I consulted it but could not find an option on setting the current work dir of the job.

**Comment by mg979** [comment]
https://mg979.github.io/tasks.vim/1-async.html#h-functions


```
async#cmd(cmd, mode, …)

@param cmd:  the command
@param mode: quickfix, buffer, terminal, external, cmdline or headless
@param ...:  can be one or two dicts
             - first is 'useropts' (user data stored in g:async_jobs[id])
             - second is 'jobopts' (merged with job options)
```

For example you could do:

    call async#cmd('ls', 'terminal', {}, {'cwd': expand('~')})

or use `buffer` (or another _mode_) if you want the output to a buffer. Note that the `cwd` is passed to the vim `job_start()` function, it's not handled by the plugin. So you must expand it. Also note that there is an empty dictionary as third argument, those are the [_user options_](https://mg979.github.io/tasks.vim/1-async.html#h-user-options).

I guess one could make an `AsyncRun` command that mimics that plugin, by parsing the arguments and then passing them to the `async#cmd` function. The commands I provided are just async wrappers for default vim commands (`Async` doesn't exists, ok), not replacements for `AsyncRun`.

If I need more specific commands, I make a task using a `.tasks` project file or the `tasks.ini` global file. That part is a bit like in [asynctasks.vim](https://github.com/skywind3000/asynctasks.vim).

But you can use functions directly or make our own commands if you prefer.

**Comment by Konfekt** [comment]
Thank you! I did not get that job options was a fixed term referring to the options passed to `job_start()` among which figures `cwd`.  A link to the Vim help on [job options](https://vimhelp.org/channel.txt.html#job-options) could clarify.

**Comment by Konfekt** [comment]
The following commands to git pull, fetch and push in the background could be of independent interest:

```vim
if exists(':Async') == 2
    command! -bang -bar -nargs=* Gpush call async#cmd('git push ' . <q-args>, 'quickfix', {'nojump': <bang>0}, {'cwd': expand(FugitiveGitDir(), ":h:S")})
    command! -bang -bar -nargs=* Gfetch call async#cmd('git fetch ' . <q-args>, 'quickfix', {'nojump': <bang>0}, {'cwd': expand(FugitiveGitDir(), ":h:S")})
    command! -bang -bar -nargs=* Gpull execute call async#cmd('git pull ' . <q-args>, 'quickfix', {'nojump': <bang>0}, {'cwd': expand(FugitiveGitDir(), ":h:S")})
endif
```

**Comment by mg979** [comment]
Those command should have `fnamemodify()`, not `expand()`.

**Comment by Konfekt** [comment]
I agree, but then tasks complains that

```vim
Errore/i eseguendo function async#cmd[17]..<SNR>429_job_start:
riga    4:
E475: Invalid value for argument cwd
```

**Comment by Konfekt** [comment]
Okay, it seems that `job_start()` does not expect a shell escaped path (`:S` causes surrounding the path `/...` by single quotes `'/...'`): Instead, it suffices:

```vim
if exists(':Async') == 2
    command! -bang -bar -nargs=* Gpush call async#cmd('git push ' . <q-args>, 'quickfix', {'nojump': <bang>0}, {'cwd': fnamemodify(FugitiveGitDir(), ":h")})
    command! -bang -bar -nargs=* Gfetch call async#cmd('git fetch ' . <q-args>, 'quickfix', {'nojump': <bang>0}, {'cwd': fnamemodify(FugitiveGitDir(), ":h")})
    command! -bang -bar -nargs=* Gpull execute call async#cmd('git pull ' . <q-args>, 'quickfix', {'nojump': <bang>0}, {'cwd': fnamemodify(FugitiveGitDir(), ":h")})
endif
```
