### ISSUE TITLE
error after b44082e9a1f7bdc2391c73d585436b7aa28dcb2b

### ISSUE THREAD

**Issue by Konfekt** [mg979/tasks.vim#9]
Calling

```vim
call async#cmd('git pull', 'quickfix', {'nojump': 0}, {'cwd': fnamemodify(FugitiveGitDir(), ":h")})
```

produces after commit b44082e9a1f7bdc2391c73d585436b7aa28dcb2b the error messages

```vim
Errore/i eseguendo function async#cmd[2]..<SNR>424_user_opts[1]..<SNR>424_default_opts:
riga    1:
E119: La funzione: bufnr richiede più argomenti
E15: Espressione non valida: { 'winid': win_getid(), 'bufnr': bufnr(), 'makeprg': s:bufvar('&makeprg'), 'grepprg': s:bufvar('&grepprg'), 'errorformat': s:bufvar('&errorformat'), 'grepformat': s:bufvar('&grepformat'), 'qfautocmd': '', 'compiler': '', 'append': 0, 'locl': 0, 'grep': 0, 'focus': 0, 'nojump': 0, 'openqf': 0, 'nosave': 0, 'wall': 0, 'keepouts': 0, 'writelogs': 0, 'outfile': '', 'errfile': '', 'noquit': 0, 'noenv': 0, 'discard': 0, 'unlisted': 0, 'hidden': 0,}
Errore/i eseguendo function async#cmd[2]..<SNR>424_user_opts:
riga    1:
E712: L'argomento di extend() deve essere una Lista o un Dizionario
```

**Comment by mg979** [comment]
Fixed?

**Comment by Konfekt** [comment]
Yes, thank you!

**Comment by Konfekt** [comment]
There seems to be another artifact remaining: After `Make`, if there is a quickfix entry, the following error message shows up:

```vim
Errore/i eseguendo function async#finish[10]..<SNR>437_cb_quickfix:
riga   15:
E716: Chiave assente dal Dizionario: cwd)
E116: Argomenti non validi per la funzione: <SNR>437_lcd_in_new_win
```

**Comment by mg979** [comment]
Fixed?

**Comment by Konfekt** [comment]
Yes, thank you. The only problem is that now always Vim interrupts asking if one wants to be brought to a finished job; I guess it is a new setting enabled by default?

**Comment by mg979** [comment]
It should only ask for jobs using location list, and if the job finishes after you have left the window, so it asks if you want to go there. Why do you say _always_? I can add a setting to control this anyway. But it shouldn't be _always_ doing this, just in the case I told you.

**Comment by Konfekt** [comment]
It does it always now and did it never before for LMake. I never left the window.

**Comment by Konfekt** [comment]
It appears right after hitting enter after :LMake in the command line (the job taking miliseconds).

**Comment by mg979** [comment]
I cannot reproduce. I run `:LMake` on a simple project, staying in the same window, and no message. Which is the full command you use? Which options?

**Comment by Konfekt** [comment]
I use `:LMake %:S` with shellcheck in a small shell file. Perhaps there is an autocmd quickly stealing the focus.

**Comment by Konfekt** [comment]
```vim
    Nome        Arg.       Indir.    Completo  Definizione
!   LMake       ?                                  call async#qfix(<q-args>, {'nojump': <bang>0, 'locl': 1})
	Impostata l'ultima volta da ~/.config/.vim/plugged/tasks.vim/plugin/async.vim

```

**Comment by Konfekt** [comment]
For example, the[quickfix-reflector plug-in](https://github.com/stefandtw/quickfix-reflector.vim) could intervene.

**Comment by mg979** [comment]
Please update. Not sure if it will be fixed but it could be related.

**Comment by Konfekt** [comment]
I did update, but the issue remains. Perhaps [vim-qf](https://github.com/romainl/vim-qf/blob/127257057c4befb8c1026a7ba7e07713af1fb5c8/plugin/qf.vim#L55) intervenes; it sets up autocmd to automatically open the quickfix window / location list window after make is run.

**Comment by mg979** [comment]
Try removing those plugins.

**Comment by mg979** [comment]
I did another update.

**Comment by Konfekt** [comment]
Thank you! It did not change anything. How about adding an option that is disabled by default and can be enabled to offer an input dialog to jump to another window? This way backwards compatibility could be retained.

**Comment by Konfekt** [comment]
> Try removing those plugins.

With a minimal vimrc probably everything will work, but, say, adding an autocmd to open the location list after `:lmake` finished is a common setting.  How about making this plug-in compatible with other people's setups by making the input dialog to jump to another window an option that is disabled by default?  This way backwards compatibility could be retained.

**Comment by Konfekt** [comment]
To reproduce (with a minimal `vimrc`):

```vim
autocmd QuickFixCmdPost lmake lwindow
```

does not open the location list window after `:Lmake`.
Instead

```vim
autocmd QuickFixCmdPost lexpr lwindow
```

opens the location list window after `:Lmake`.

However, the two autocmds (notice that the quickfix-list `make` interferes with location-list `lexpr`)

```vim
autocmd QuickFixCmdPost make cwindow
autocmd QuickFixCmdPost lexpr lwindow
````

open the said input dialog instead of the location list window.

**Comment by mg979** [comment]
>  How about making this plug-in compatible with other people's setups by making the input dialog to jump to another window an option that is disabled by default?

https://github.com/mg979/tasks.vim/commit/9b47a8dade47fa418af31d850ee386117fe2e272

Ok I'll make it disabled by default, but you can set the option in the meantime.

**Comment by Konfekt** [comment]
I saw the commit too late; it is a useful feature and could be made default, but then better cooperate with these QuickFixCmdPost autocmds opening the quickfix/location list window; or at least document how they should be adapted.

**Comment by Konfekt** [comment]
Let's clarify the issue by putting https://github.com/mg979/tasks.vim/issues/9#issuecomment-922940347 into a separate thread
